🐛 rich-pixels bugs
* 🐛 rich-pixels bugs

A problem in rich-pixels caused this error `ImportError: cannot import name 'Resampling' from 'PIL.Image'` this commit fixes it by requiring Pillow `Pillow>=9.1.0`

* 🐛 rich-pixels bugs

---------

Co-authored-by: Justin Flannery <juftin@juftin.com>